### ISSUE TITLE
Error getting password. Follow the instructions and try again.

### ISSUE THREAD

**Issue by skosow** [karlvr/homebridge-roomba2#41]
When I run the script, I get all the information about the robot except the password.

The output ends with the message "Error getting password. Follow the instructions and try again."

**Comment by hardstriker** [comment]
Also having same issue. I get all the other information including the blid, but it errors out with the above response.

**Comment by knavabi** [comment]
Same issue!

**Comment by BlakeBoxberger** [comment]
I had this issue too. I was also getting all of the information about the robot except for the password. 

I was holding the POWER button instead of the HOME button. 

Make sure you hold down the HOME button, it'll beep, and then the wifi icon will start blinking a few seconds later. Press any key and it'll give you the password.

(You guys have no idea how many times I tried this accidentally using the power button.)

**Comment by vsenn** [comment]
I had the same issue with my Roomba 981, but I was mistakenly keep pressing CLEAN (power) button same as @BlakeBoxberger robot blinks and plays all required sounds, but didn't provider required password config ) 
It must be HOME button instead, small "Home" pictogram on left in my case.
