### ISSUE TITLE
How to get BLID & password

### ISSUE THREAD

**Issue by m-opserc** [karlvr/homebridge-roomba2#59]
I am an extreme newbie to this so I apologize in advance. Any help would be greatly appreciate. I am having trouble getting the blid and password necessary to run this plugin for my Roomba.
I am not really sure what the author meant by CD into where your plugins are installed.
I have typed in sudo npm run getrobotpwd 192.168.x.xxx (Roomba actual address) into the homebridge terminal and all I get is "npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /var/lib/homebridge/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/lib/homebridge/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-11T05_33_42_760Z-debug.log."
I have looked at the config options in homebridge UI and attempted to place the same command with no luck as well. 
I have also placed that same command in my Mac terminal with no luck. 
Im pretty certain once I can obtain the blid and password the rest I can do on my own. 
Again any help would be greatly appreciated.

**Comment by rcoletti116** [comment]
CD means 'change directory.' It's a linux command. You need to know where the homebridge-roomba2 plugin is installed and run the command from within that directory. 

For example, I'm running the Official Raspberry Pi image and my plugins are installed in /usr/local/lib/node_modules/ so in order to change to that directory I would type `cd /usr/local/lib/node_modules/`. 

If you don't know where your plugins are installed, you can type the command `npm root -g` which may help (if you installed your plugins as global packages). Maybe this will help - how did you install homebridge and how did you install this plugin?

**Comment by m-opserc** [comment]
It took me a couple of days but I was finally able to get it. I am using the official imager from homebridge for the pi. Terminal was giving me issues at first with those commands (I probably missed typed the commands) I am new to running codes on terminal so I couldn't figure out what cd meant and how to correctly type the command in terminal but its working flawlessly now. Thank you for your help/response.

**Comment by karlvr** [comment]
@m-opserc great that you have it sorted. @rcoletti116 thank you for helping out. I've made some improvements to the README in this respect and we have some more coming, hopefully, in #61.
